"""
AI Coach
generated by Mistral
"""

import sys
from pathlib import Path

import streamlit as st

sys.path.insert(0, str(Path(__file__).parent.parent))
from api_client import get_ai_motivation, get_ai_nutrition_advice, get_ai_workout_plan, get_goal

st.set_page_config(page_title="AI Coach", layout="wide")
st.title("🤖 AI Coach")

# ======================================================
# Context warning
# ======================================================

goal = get_goal()
if not goal:
    st.warning(
        "To get personalized advice, please set your fitness goal in the Dashboard page first."
    )
else:
    st.success(f"Your current fitness goal: **{goal['goal_type']}** - {goal.get('weekly_workouts', 3)} workouts/week")

st.markdown("Push a button for personalized advice based on your fitness data and goals.")
st.divider()