"""
AI Coach
generated by Mistral
"""

import sys
from pathlib import Path

import streamlit as st

sys.path.insert(0, str(Path(__file__).parent.parent))
from api_client import get_ai_motivation, get_ai_nutrition_advice, get_ai_workout_plan, get_goal

st.set_page_config(page_title="AI Coach", layout="wide")
st.title("🤖 AI Coach")

# ======================================================
# Context warning
# ======================================================

goal = get_goal()
if not goal:
    st.warning(
        "To get personalized advice, please set your fitness goal in the Dashboard page first."
    )
else:
    st.success(f"Your current fitness goal: **{goal['goal_type']}** - {goal.get('weekly_workouts', 3)} workouts/week")

st.markdown("Push a button for personalized advice based on your fitness data and goals.")
st.divider()

# ======================================================
# AI advice
# ======================================================

col1, col2, col3 = st.columns(3)

with col1:
    st.subheader("Workout Plan")
    st.markdown("Get a personalized workout plan based on your fitness goal and workout history.")
    if st.button("Generate Workout Plan", type="primary", use_container_width=True):
        with st.spinner("Generating workout plan..."):
            try:
                result = get_ai_workout_plan()
                st.session_state["workout_plan"] = result
            except Exception as e:
                st.error(f"Error generating workout plan: {e}")

    if "workout_plan" in st.session_state:
        st.markdown(st.session_state["workout_plan"])

with col2:
    st.subheader("Nutrition Advice")
    st.markdown("Get personalized nutrition advice based on your logged meals and fitness goals.")
    if st.button("Generate Nutrition Advice", type="primary", use_container_width=True):
        with st.spinner("Generating nutrition advice..."):
            try:
                result = get_ai_nutrition_advice()
                st.session_state["nutrition_advice"] = result
            except Exception as e:
                st.error(f"Error generating nutrition advice: {e}")

    if "nutrition_advice" in st.session_state:
        st.markdown(st.session_state["nutrition_advice"])

with col3:
    st.subheader("Motivation")
    st.markdown("Get a personalized motivational message to keep you on track with your fitness journey.")
    if st.button("Get Motivation", type="primary", use_container_width=True):
        with st.spinner("Generating motivation..."):
            try:
                result = get_ai_motivation()
                st.session_state["motivation"] = result
            except Exception as e:
                st.error(f"Error generating motivation: {e}")

    if "motivation" in st.session_state:
        st.markdown(st.session_state["motivation"])

st.divider()
st.caption("Note: AI-generated advice is based on your logged data and goals, but always consult with a fitness professional for personalized guidance.")